[target.xtensa-esp32-none-elf]
runner = "espflash -T ./partitions.csv flash --monitor --chip esp32 --erase-parts otadata"

[env]

[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
]

target = "xtensa-esp32-none-elf"

[unstable]
build-std = ["core"]
